### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by tooolbox** [zhon12345/Tavern-Keeper-Website#2]
The actual Tavern Keeper instance appears to be down, it's 302ing.

**Comment by zhon12345** [comment]
The bot is online and working as expected

**Comment by zhon12345** [comment]
I think you're mistaking my project with someone else's, my project is a discord not called tavern keeper and this repo is for it's website

**Comment by tooolbox** [comment]
I gotcha, apologize for the mistake.
